# -*- coding: utf-8 -*-
"""machinelearningb50exp10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vygYkfVUVHH-hixdBQlbSqxY49iaqYM-
"""

# Import required libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import io
from google.colab import files

# Load the dataset
uploaded = files.upload()

# Set a general style for the plots
sns.set(style="whitegrid")

plt.figure(figsize=(8, 6))
netflix_data = pd.read_csv(io.BytesIO(uploaded['netflix1.csv']))
plt.title('Count of Movies and TV Shows on Netflix')
plt.xlabel('Type')
plt.ylabel('Count')
plt.show()

# Get the top 10 countries by count
top_countries = netflix_data['country'].value_counts().head(10)

plt.figure(figsize=(10, 6))
sns.barplot(y=top_countries.index, x=top_countries.values, palette='magma')
plt.title('Top 10 Countries by Number of Netflix Titles')
plt.xlabel('Count')
plt.ylabel('Country')
plt.show()

plt.figure(figsize=(10, 6))
sns.countplot(data=netflix_data, y='rating', order=netflix_data['rating'].value_counts().index, palette='plasma')
plt.title('Distribution of Ratings')
plt.xlabel('Count')
plt.ylabel('Rating')
plt.show()

plt.figure(figsize=(12, 6))
sns.histplot(netflix_data['release_year'], bins=30, kde=True, color='skyblue')
plt.title('Distribution of Netflix Titles by Release Year')
plt.xlabel('Release Year')
plt.ylabel('Count')
plt.show()

# Filter for movies only and convert duration to numeric
movies_data = netflix_data[netflix_data['type'] == 'Movie'].copy()
movies_data['duration'] = movies_data['duration'].str.replace(' min', '').astype(float)

plt.figure(figsize=(12, 6))
sns.histplot(movies_data['duration'], bins=30, color='lightcoral', kde=True)
plt.title('Distribution of Movie Durations')
plt.xlabel('Duration (minutes)')
plt.ylabel('Count')
plt.show()

